-- MySQL Script generated by MySQL Workbench
-- 04/29/17 13:43:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco` VARCHAR(255) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoafisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pessoafisica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pessoafisica` (
  `idpessoafisica` INT NOT NULL,
  `cpf` VARCHAR(45) NULL,
  `identidade` VARCHAR(45) NULL,
  `tipoidentidade` VARCHAR(45) NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpessoafisica`, `cliente_idcliente`),
  INDEX `fk_pessoafisica_cliente1_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_pessoafisica_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoajuridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pessoajuridica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pessoajuridica` (
  `idpessoajuridica` INT NOT NULL,
  `cnpj` VARCHAR(45) NULL,
  `razaoSocial` VARCHAR(255) NULL,
  `inscricaoEstadual` VARCHAR(45) NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpessoajuridica`, `cliente_idcliente`),
  INDEX `fk_pessoajuridica_cliente1_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_pessoajuridica_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atendimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`atendimento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`atendimento` (
  `idatendimento` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `data` DATE NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idatendimento`),
  INDEX `fk_atendimento_cliente_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_atendimento_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
